services:
  - type: web
    name: wow-burger-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: wow_burger
      - key: DB_SSL
        value: true
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://wow-burger-nine.vercel.app
      - key: BASE_URL
        sync: false
